services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  order-service:
    build:
      context: .
      dockerfile: ./order-container/Dockerfile
    container_name: order-service
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    restart: unless-stopped

volumes:
  postgres_data: