server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  application:
    name: order-service
