spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: order_user
    password: order_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never

server:
  port: 8080